const propertyData = [
    {
        id: "MErPrrLwvAg",
        title: "Villa Serena",
        price: 8950000,
        location: "Bel Air, Los Angeles",
        type: "Luxury Villa",
        beds: 5,
        baths: 6,
        sqft: 7200,
        coords: [34.0934, -118.4491],
        image: "assets/villa_serena_1777634205747.png",
        featured: true,
        description: "An extraordinary modern villa offering panoramic views of the Pacific."
    },
    {
        id: "hkwLUs7gDe8",
        title: "The Pinnacle",
        price: 12500000,
        location: "Bel Air, Los Angeles",
        type: "Penthouse",
        beds: 4,
        baths: 4.5,
        sqft: 4800,
        coords: [34.0905, -118.4475],
        image: "assets/the_pinnacle_1777634220391.png",
        featured: true,
        description: "A breathtaking penthouse situated in the heart of Bel Air."
    },
    {
        id: "onEnkRSJLco",
        title: "Château Lumière",
        price: 18700000,
        location: "Bel Air, Los Angeles",
        type: "Estate",
        beds: 8,
        baths: 10,
        sqft: 12500,
        coords: [34.0915, -118.4520],
        image: "assets/chateau_lumiere_1777634237744.png",
        featured: true,
        description: "A legendary estate nestled in the Bel Air hills."
    },
    {
        id: "uVZJZFT3jze",
        title: "Azure Heights",
        price: 6200000,
        location: "Bel Air, Los Angeles",
        type: "Modern Mansion",
        beds: 4,
        baths: 5,
        sqft: 5800,
        coords: [34.0880, -118.4460],
        image: "assets/modern_glass_villa_1777636244114.png",
        featured: false,
        description: "A minimalist masterpiece tucked into the lush hills."
    },
    {
        id: "cc1xE17XcJy",
        title: "The Haven",
        price: 14800000,
        location: "Bel Air, Los Angeles",
        type: "Estate",
        beds: 6,
        baths: 7,
        sqft: 8100,
        coords: [34.0850, -118.4440],
        image: "assets/tropical_island_estate_1777636279525.png",
        featured: false,
        description: "A secluded sanctuary offering ultimate privacy and luxury."
    },
    {
        id: "2nGHmCYLXGo",
        title: "Emerald Manor",
        price: 9250000,
        location: "Bel Air, Los Angeles",
        type: "Historic Estate",
        beds: 7,
        baths: 8,
        sqft: 11200,
        coords: [34.0820, -118.4420],
        image: "assets/historic_manor_1777636263361.png",
        featured: false,
        description: "A timeless historic estate with grand architecture."
    },
    {
        id: "7gjJk4p3W62",
        title: "Alpine Peak",
        price: 11400000,
        location: "Bel Air, Los Angeles",
        type: "Modern Villa",
        beds: 5,
        baths: 5.5,
        sqft: 5600,
        coords: [34.0800, -118.4400],
        image: "assets/aspen_mountain_chalet_1777636296561.png",
        featured: false,
        description: "A stunning mountain-inspired modern villa."
    },
    {
        id: "belAirVista",
        title: "Bel Air Vista",
        price: 24500000,
        location: "Bel Air, Los Angeles",
        type: "Mega Mansion",
        beds: 10,
        baths: 12,
        sqft: 22000,
        coords: [34.0950, -118.4550],
        image: "assets/luxury_villa_dusk.png",
        featured: false,
        description: "One of the most expansive views in the entire city."
    }
];
